export const workingStatuses = [
  // Orchestral/scientific
  "Orchestrating...",
  "Conducting...",
  "Calibrating...",
  "Aligning...",
  "Synthesizing...",
  "Accumulating...",
  "Channeling...",
  "Harmonizing...",
  "Sequencing...",
  "Distilling...",
  "Abstracting...",
  "Indexing...",
  "Rendering...",
  "Parsing...",
  "Encoding...",
  // Poetic (2 words max)
  "Mapping void...",
  "Measuring silence...",
  "Breathing between...",
  "Charting flow...",
  "Tracing circuits...",
  "Crossing threshold...",
  "Consulting ether...",
  "Perceiving order...",
  "Weaving graphs...",
  "Curating chaos...",
  // Cryptic bytes/hex
  "0xCAFEBABE...",
  "0xDEADBEEF...",
  "0xC0FFEE...",
  "0xFF00FF...",
  "0x8BADF00D...",
  "0xFACEFEED...",
  "0xBAADF00D...",
  "0x1BADB002...",
  // Binary
  "10110010...",
  "11001001...",
  "01110011...",
  // Symbols
  "∿∿∿",
  "◈◈◈",
  "⟁⟁⟁",
  "∴∴∴",
  "⋮⋮⋮",
  // Cryptic words
  "Defragmenting...",
  "Coalescing...",
  "Interleaving...",
  "Transposing...",
  "Inverting...",
  "Permuting...",
  "Bifurcating...",
  "Reticulating...",
  "Entangling...",
];
